MappingApi\Domain\Geography\Model\Country:
  type: entity
  repositoryClass: MappingApi\Infrastructure\Repository\Doctrine\CountryRepository
  table: country
  schema: schema_name # The schema the table lies in, for platforms that support schemas (Optional, >= 2.5)
  readOnly: true
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: false
    code:
      type: string
      length: 2
      nullable: false
    currency:
      type: string
      length: 3
      nullable: false
    lifecycleCallbacks: {  }